import { DataSource } from '../models';

export const MOCK_DATA_SOURCE: DataSource = [
  {
    id: '1',
    name: 'Electronics',
    children: [
      {
        id: '1-1',
        name: 'Phones',
        children: [
          {
            id: '1-1-1',
            name: 'Android',
            children: [
              {
                id: '1-1-1-1',
                name: 'Samsung',
                children: [
                  { id: '1-1-1-1-1', name: 'S8' },
                  { id: '1-1-1-1-2', name: 'S9' },
                  { id: '1-1-1-1-3', name: 'S10' },
                  { id: '1-1-1-1-4', name: 'S20' },
                  { id: '1-1-1-1-5', name: 'S21' },
                  { id: '1-1-1-1-6', name: 'S22' },
                  { id: '1-1-1-1-7', name: 'S23' },
                  { id: '1-1-1-1-8', name: 'S24' },
                  { id: '1-1-1-1-9', name: 'Note 8' },
                  { id: '1-1-1-1-10', name: 'Note 9' },
                  { id: '1-1-1-1-11', name: 'Note 10' },
                  { id: '1-1-1-1-12', name: 'Note 20' },
                  { id: '1-1-1-1-13', name: 'A50' },
                  { id: '1-1-1-1-14', name: 'A51' },
                  { id: '1-1-1-1-15', name: 'A52' },
                ],
              },
              {
                id: '1-1-1-2',
                name: 'Google',
                children: [
                  { id: '1-1-1-2-1', name: 'Pixel 1' },
                  { id: '1-1-1-2-2', name: 'Pixel 2' },
                  { id: '1-1-1-2-3', name: 'Pixel 3' },
                  { id: '1-1-1-2-4', name: 'Pixel 4' },
                  { id: '1-1-1-2-5', name: 'Pixel 5' },
                  { id: '1-1-1-2-6', name: 'Pixel 6' },
                  { id: '1-1-1-2-7', name: 'Pixel 7' },
                  { id: '1-1-1-2-8', name: 'Pixel 8' },
                  { id: '1-1-1-2-9', name: 'Pixel 8 Pro' },
                  { id: '1-1-1-2-10', name: 'Pixel 8a' },
                  { id: '1-1-1-2-11', name: 'Pixel 7a' },
                  { id: '1-1-1-2-12', name: 'Pixel 6a' },
                ],
              },
              {
                id: '1-1-1-3',
                name: 'OnePlus',
                children: [
                  { id: '1-1-1-3-1', name: '6' },
                  { id: '1-1-1-3-2', name: '6T' },
                  { id: '1-1-1-3-3', name: '7' },
                  { id: '1-1-1-3-4', name: '7T' },
                  { id: '1-1-1-3-5', name: '8' },
                  { id: '1-1-1-3-6', name: '8T' },
                  { id: '1-1-1-3-7', name: '9' },
                  { id: '1-1-1-3-8', name: '9 Pro' },
                  { id: '1-1-1-3-9', name: '10' },
                  { id: '1-1-1-3-10', name: '10 Pro' },
                  { id: '1-1-1-3-11', name: '11' },
                  { id: '1-1-1-3-12', name: '12' },
                ],
              },
            ],
          },
          {
            id: '1-1-2',
            name: 'iOS',
            children: [
              {
                id: '1-1-2-1',
                name: 'iPhone',
                children: [
                  { id: '1-1-2-1-1', name: '8' },
                  { id: '1-1-2-1-2', name: 'X' },
                  { id: '1-1-2-1-3', name: 'XR' },
                  { id: '1-1-2-1-4', name: 'XS' },
                  { id: '1-1-2-1-5', name: '11' },
                  { id: '1-1-2-1-6', name: '11 Pro' },
                  { id: '1-1-2-1-7', name: '12' },
                  { id: '1-1-2-1-8', name: '12 Pro' },
                  { id: '1-1-2-1-9', name: '13' },
                  { id: '1-1-2-1-10', name: '13 Pro' },
                  { id: '1-1-2-1-11', name: '14' },
                  { id: '1-1-2-1-12', name: '14 Pro' },
                  { id: '1-1-2-1-13', name: '15' },
                  { id: '1-1-2-1-14', name: '15 Pro' },
                ],
              },
            ],
          },
        ],
      },
      {
        id: '1-2',
        name: 'Laptops',
        children: [
          {
            id: '1-2-1',
            name: 'Apple',
            children: [
              { id: '1-2-1-1', name: 'MacBook Air' },
              { id: '1-2-1-2', name: 'MacBook Pro 13' },
              { id: '1-2-1-3', name: 'MacBook Pro 14' },
              { id: '1-2-1-4', name: 'MacBook Pro 16' },
              { id: '1-2-1-5', name: 'MacBook 12' },
              { id: '1-2-1-6', name: 'MacBook Retina' },
              { id: '1-2-1-7', name: 'MacBook Pro 2015' },
              { id: '1-2-1-8', name: 'MacBook Pro 2016' },
              { id: '1-2-1-9', name: 'MacBook Pro 2017' },
              { id: '1-2-1-10', name: 'MacBook Pro 2018' },
              { id: '1-2-1-11', name: 'MacBook Pro 2019' },
              { id: '1-2-1-12', name: 'MacBook Pro 2020' },
            ],
          },
          {
            id: '1-2-2',
            name: 'Dell',
            children: [
              { id: '1-2-2-1', name: 'XPS 13' },
              { id: '1-2-2-2', name: 'XPS 15' },
              { id: '1-2-2-3', name: 'XPS 17' },
              { id: '1-2-2-4', name: 'Inspiron 13' },
              { id: '1-2-2-5', name: 'Inspiron 15' },
              { id: '1-2-2-6', name: 'Inspiron 17' },
              { id: '1-2-2-7', name: 'Latitude 5400' },
              { id: '1-2-2-8', name: 'Latitude 7400' },
              { id: '1-2-2-9', name: 'Precision 5550' },
              { id: '1-2-2-10', name: 'Precision 7550' },
              { id: '1-2-2-11', name: 'Alienware m15' },
              { id: '1-2-2-12', name: 'Alienware m17' },
            ],
          },
          {
            id: '1-2-3',
            name: 'Lenovo',
            children: [
              { id: '1-2-3-1', name: 'ThinkPad X1 Carbon' },
              { id: '1-2-3-2', name: 'ThinkPad T14' },
              { id: '1-2-3-3', name: 'ThinkPad T15' },
              { id: '1-2-3-4', name: 'ThinkPad P1' },
              { id: '1-2-3-5', name: 'ThinkPad L14' },
              { id: '1-2-3-6', name: 'ThinkPad E14' },
              { id: '1-2-3-7', name: 'Yoga 7i' },
              { id: '1-2-3-8', name: 'Yoga 9i' },
              { id: '1-2-3-9', name: 'Legion 5' },
              { id: '1-2-3-10', name: 'Legion 7' },
              { id: '1-2-3-11', name: 'IdeaPad 3' },
              { id: '1-2-3-12', name: 'IdeaPad 5' },
            ],
          },
        ],
      },
    ],
  },
  {
    id: '2',
    name: 'Furniture',
    children: [
      {
        id: '2-1',
        name: 'Chairs',
        children: [
          { id: '2-1-1', name: 'Office' },
          { id: '2-1-2', name: 'Living Room' },
        ],
      },
    ],
  },
];
